# Generated by Django 4.0.4 on 2022-05-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_a', models.DateTimeField(verbose_name='date')),
                ('desc_a', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_s', models.DateTimeField(verbose_name='date')),
                ('field', models.CharField(max_length=60, verbose_name='field')),
                ('skill', models.TextField(verbose_name='skill')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='year')),
                ('company', models.CharField(max_length=60, verbose_name='company')),
                ('job', models.CharField(max_length=60, verbose_name='job')),
            ],
        ),
    ]
