# Generated by Django 4.0.4 on 2022-05-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='award',
            name='date_a',
            field=models.TextField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='date_s',
            field=models.TextField(verbose_name='date'),
        ),
    ]
