# Generated by Django 4.0.4 on 2022-05-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_image_alter_award_date_a_alter_skill_date_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_img', models.ImageField(upload_to='', verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='award',
            name='date_a',
            field=models.TextField(null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='award',
            name='desc_a',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='date_s',
            field=models.TextField(null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='field',
            field=models.CharField(max_length=60, null=True, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.TextField(null=True, verbose_name='skill'),
        ),
        migrations.AlterField(
            model_name='work',
            name='company',
            field=models.CharField(max_length=60, null=True, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='work',
            name='job',
            field=models.CharField(max_length=60, null=True, verbose_name='job'),
        ),
        migrations.AlterField(
            model_name='work',
            name='year',
            field=models.IntegerField(null=True, verbose_name='year'),
        ),
    ]
