# Generated by Django 4.0.4 on 2022-05-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_image_alter_award_date_a_alter_award_desc_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('pro_img', models.ImageField(upload_to='', verbose_name='image')),
                ('desc', models.TextField(verbose_name='description')),
                ('city', models.CharField(max_length=60, verbose_name='city')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
