# Generated by Django 4.0.4 on 2022-05-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_info_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='pro_img',
            new_name='proimg',
        ),
    ]
