# Generated by Django 4.0.4 on 2022-05-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_info_proimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='proimg',
            field=models.ImageField(upload_to='images/', verbose_name='image'),
        ),
    ]
