# Generated by Django 4.0.4 on 2022-05-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_info_proimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='proimg',
        ),
        migrations.AddField(
            model_name='info',
            name='img',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='image'),
        ),
    ]
